### ISSUE TITLE
[feature] Show directory architecture in ormb UI

### ISSUE THREAD

**Issue by gaocegege** [kleveross/ormb#42]
**Is this a BUG REPORT or FEATURE REQUEST?**:

/kind feature

**What happened**:

Visualize the model directory structure in UI

**What you expected to happen**:

**How to reproduce it (as minimally and precisely as possible)**:

**Anything else we need to know?**:

**Comment by gaocegege** [comment]
/assign @simon-cj 

Maybe you can try to investigate if you are free.

**Comment by simon-cj** [comment]
The harbor store model as a blob, and it is not store the directory metadata, so if we want to show it, we must UnTar the model like `ormb export`,  there are two problems:
1. if klever-model-registry want to UnTar the model, it must pull the model, if the model is too big, the performance will be poor.
2. otherwise， if the model-registry can reach the storage of harbor, it will be OK, but will limit the deploy method of harbor.

@gaocegege  WDYT

**Comment by gaocegege** [comment]
> otherwise， if the model-registry can reach the storage of harbor, it will be OK, but will limit the deploy method of harbor.

It does not work. Harbor do not care about the unzipped files. Maybe we could record the directory arch in config or a new content layer.

**Comment by simon-cj** [comment]
Can pull only one layer？

**Comment by gaocegege** [comment]
Why should we pull only one layer?
