### ISSUE TITLE
[feature] Investigate how to support Nvidia TensorRT format

### ISSUE THREAD

**Issue by gaocegege** [kleveross/ormb#92]
**Is this a BUG REPORT or FEATURE REQUEST?**:

> Uncomment only one, leave it on its own line:
>
> /kind bug
> /kind feature

**What happened**:

Nvidia Triton Server has its own model repository layout. We decide using the triton server as the default model inference server, then we should investigate how to support the layout well.

/cc @simon-cj 

**What you expected to happen**:

**How to reproduce it (as minimally and precisely as possible)**:

**Anything else we need to know?**:

**Comment by simon-cj** [comment]
ok, I wiil do it soon

**Comment by gaocegege** [comment]
It is assigned to @FogDong .

**Comment by gaocegege** [comment]
Because it is more about model inference.

**Comment by gaocegege** [comment]
I think we should consider if we generate config.pbtxt in modeljob.

**Comment by FogDong** [comment]
In our former product `Clever`, the `config.pbtxt` file is generated from `manifest.json` when the model serving is created. 
Since the ormb users may need to deploy models using triton server without any other manual operations, I think we should generate `config.pbtxt` from `ormbfile.yaml` when users save the model in ormb.

For better scalability, we also need a command like `ormb env`(similar to  `go env`) where we can set params like `TRITON=on` and the `config.pbtxt` will only be generated when the variable is on.

WDYT @gaocegege

**Comment by gaocegege** [comment]
We have a CRD modeljob which will be used to extract model signatures, can we try to generate pbtxt in the modeljob?
